server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-list-repair
    username: postgres
    password: isilinda
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka