server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: autofix-car
          uri: lb://autofix-car:8090
          predicates:
            - Path=/car/**

        - id: autofix-repair
          uri: lb://autofix-repair:8091
          predicates:
            - Path=/repair/**

        - id: autofix-list-repair
          uri: lb://autofix-list-repair:8092
          predicates:
            - Path=/repair-list/**