server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: autofix-car
          uri: lb://autofix-car
          predicates:
            - Path=/car/**

        - id: autofix-repair
          uri: lb://autofix-repair
          predicates:
            - Path=/repair/**

        - id: autofix-list-repair
          uri: lb://autofix-list-repair
          predicates:
            - Path=/repair-list/**