server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: autofix-car
          uri: lb://autofix-car
          predicates:
            - Path=/api/car/**

        - id: autofix-repairs
          uri: lb://autofix-repairs
          predicates:
            - Path=/api/repairs/**

        - id: autofix-list-repair
          uri: lb://autofix-list-repair
          predicates:
            - Path=/api/repair-list/**